version: '3'
services:
  aparapi_native_windows_builder:
    container_name: aparapi_native_builder-worker
    image: 'aparapi/aparapi-native-builder-image-worker:latest'
    build:
      context: .
    user: "$UID:$GID"
    volumes:
      - '${PWD}:/usr/src/app'
